// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../src/PoseidonDeployer.sol";

/// @title CompatCheck
/// @notice Verifies that the on-chain Poseidon (PoseidonDeployer bytecode, from circomlibjs)
///         produces the SAME outputs as circomlibjs in JS.
///
///         A mismatch here means ZK proofs will ALWAYS fail on-chain silently.
///         Expected values are computed by: node packages/circuits/scripts/check-poseidon-compat.js
contract CompatCheckTest is Test {

    // ── Expected values from circomlibjs (JS ground truth) ──────────────────
    // Generated by: node packages/circuits/scripts/check-poseidon-compat.js
    uint256 constant JS_POSEIDON_1         = 0x29176100eaa962bdc1fe6c654d6a3c130e96a4d1168b33848b897dc502820133;
    uint256 constant JS_POSEIDON_1_2       = 0x115cc0f5e7d690413df64c6b9662e9cf2a3617f2743245519e19607a4417189a;
    uint256 constant JS_POSEIDON_MSK42     = 0x1b408dafebeddf0871388399b1e53bd065fd70f18580be5cdde15d7eb2c52743;
    uint256 constant JS_POSEIDON_NUL42_999 = 0x2e7a46d8636044c5d5c9eea7b51b1a2964acab38cfd49298924ee9e03e462db2;

    IPoseidon1 poseidon1;
    IPoseidon2 poseidon2;

    function setUp() public {
        poseidon1 = IPoseidon1(PoseidonDeployer.deployPoseidon1());
        poseidon2 = IPoseidon2(PoseidonDeployer.deployPoseidon2());
    }

    /// @dev Poseidon([1]) on-chain must equal circomlibjs Poseidon([1])
    function test_poseidonCompat_single_1() public view {
        uint256 result = poseidon1.poseidon([uint256(1)]);
        assertEq(result, JS_POSEIDON_1,
            "Poseidon([1]): on-chain != circomlibjs. ZK proofs will ALWAYS fail.");
    }

    /// @dev Poseidon([1, 2]) on-chain must equal circomlibjs Poseidon([1, 2])
    function test_poseidonCompat_pair_1_2() public view {
        uint256 result = poseidon2.poseidon([uint256(1), uint256(2)]);
        assertEq(result, JS_POSEIDON_1_2,
            "Poseidon([1,2]): on-chain != circomlibjs. Merkle hashing is broken.");
    }

    /// @dev Poseidon([42]) is the commitment for msk=42 (used in integration test)
    function test_poseidonCompat_commitment_msk42() public view {
        uint256 result = poseidon1.poseidon([uint256(42)]);
        assertEq(result, JS_POSEIDON_MSK42,
            "Poseidon([42]): commitment mismatch. Registration and proof will diverge.");
    }

    /// @dev Poseidon([42, 999]) is the nullifier for msk=42, circleId=999
    function test_poseidonCompat_nullifier_msk42_cid999() public view {
        uint256 result = poseidon2.poseidon([uint256(42), uint256(999)]);
        assertEq(result, JS_POSEIDON_NUL42_999,
            "Poseidon([42,999]): nullifier mismatch. joinCircle will always revert.");
    }

    /// @dev Zero input is a valid field element and must be handled
    function test_poseidonCompat_zero() public view {
        uint256 r1 = poseidon1.poseidon([uint256(0)]);
        uint256 r2 = poseidon1.poseidon([uint256(0)]);
        assertEq(r1, r2, "Poseidon([0]) must be deterministic");
        assertGt(r1, 0, "Poseidon([0]) should be nonzero");
    }

    /// @dev Poseidon is NOT commutative: Poseidon([a,b]) != Poseidon([b,a])
    function test_poseidonNonCommutative() public view {
        uint256 ab = poseidon2.poseidon([uint256(1), uint256(2)]);
        uint256 ba = poseidon2.poseidon([uint256(2), uint256(1)]);
        assertNotEq(ab, ba, "Poseidon must be non-commutative (input order matters)");
    }
}
